# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.6
  
matrix:
  allow_failures:
  - julia: nightly
  
notifications:
  email: false

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia --code-coverage test/runtests.jl
  
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("VaderSentiment")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
