name = "VaderSentiment"
uuid = "d53efdab-7ba5-41df-97a4-bb2a6cf1b478"
authors = ["nusretipek <nusretipek@yandex.com>"]
version = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0.5"
